language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master