version: "3.1"

services:
    mongo:
        image: mongo:4.4.3-bionic
        restart: always
        volumes:
            - type: bind
              source: ./mongo_init.js
              target: /docker-entrypoint-initdb.d/mongo_init.js
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: admin

    mysql:
        image: mysql:8.0.23
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
            - "33060:33060"
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pwd
            MYSQL_DATABASE: busynest
            MYSQL_USER: sa
            MYSQL_PASSWORD: password
