version: "3.1"

services:
    mongo:
        image: mongo:4.4.3-bionic
        restart: always
        volumes:
            - type: bind
              source: ./mongo_init.js
              target: /docker-entrypoint-initdb.d/mongo_init.js
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: admin
