swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Bizhub

host: localhost:3000

basePath: /

schemes: 
    - http

consumes:
    - application/json

produces:
    - application/json

# Describe your paths here
paths:
    /timesheets:
        # This is a HTTP operation
        get:
          # Describe this verb here. Note: you can use markdown
          description: |
            Gets `Timesheet` objects.
            Optional query param of **size** determines
            size of returned array
          operationId: getTimesheets
          summary: 'get timesheets'
          # This is array of GET operation parameters:
          parameters:
            # An example parameter that is in query and is required
            -   name: size
                in: query
                description: Size of array
                required: true
                type: number
                format: double
          # Expected responses for this operation:
          responses:
            # Response code
            200:
                description: Successful response
                # A schema describing your response object.
                # Use JSON Schema format
                schema:
                    title: ArrayOfTimesheets
                    type: array
                    items:
                      title: Timesheet
                      type: object
                      properties:
                        id:
                          type: number
                          readOnly: true
                        submit_date:
                          type: string
                          format: date-time
                          
    /timesheets/{id}:
        get:
            description: |
                Gets a specific `Timesheet` object.
            operationId: getTimesheetById
            summary: 'get timesheet by id'
            parameters: 
            -   name: "id"
                in: "path"
                description: "ID of pet to return"
                required: true
                type: "integer"
                format: "int64"
            responses:
                200:
                    description: Successful response
                    schema:
                        title: Timesheet
                        type: object
                        properties:
                            id:
                                type: number
                                readOnly: true
                            submit_date:
                                type: string
                                format: date-time