swagger: '2.0'

info:
  version: 1.0.0
  title: Bizhub
  description: Bizhub API resources and documentation

host: localhost:3000

basePath: /

schemes: 
  - http

consumes:
  - application/json

produces:
  - application/json

paths:
  /organizations:
    get:
      description: |
        Gets list of Organizations.
      operationId: getOrganizations
      summary: get organizations
      tags:
      - organization
      parameters:
      - $ref: "#/parameters/from"
      - $ref: "#/parameters/size"
      responses:
        200:
          description: Sucessful response
          schema:
            $ref: "#/definitions/Organizations"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
    post:
      description: |
        Create a new `Organization`
      operationId: createOrganization
      summary: create organization
      tags:
      - organization
      parameters:
      - name: organization
        in: body
        required: true
        description: organization to create
        schema:
          $ref: "#/definitions/NewOrganization"
      responses:
        201:
          description: Sucessfully created organization
          schema:
            $ref: "#/definitions/Organization"
  
  /organizations/{id}:
    get:
      description: |
        Get a specific `Organization`
      operationId: getOrganizationById
      summary: get organization by id
      tags:
      - organization
      parameters:
      - name: id
        in: path
        description: ID of organization to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Sucessfull response
          schema:
            $ref: "#/definitions/Organization"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
          
  /organizations/{id}/offices:
    get:
      description: |
        Get offices of an `Organization`
      operationId: getOrganizationOffices
      summary: get organization offices
      tags:
      - organization
      parameters:
      - name: id
        in: path
        description: ID of organization
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successfull response
          schema:
            $ref: "#/definitions/Offices"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

    post:
      description: |
        Create new office for the organization
      operationId: createOrganizationOffice
      summary: create organization office
      tags:
      - organization
      parameters:
      - name: id
        in: path
        description: ID of organization
        required: true
        type: integer
        format: int64
      - name: office
        in: body
        required: true
        description: office to create
        schema:
          $ref: "#/definitions/NewOffice"
      responses:
        201:
          description: Created successfully
          schema:
            $ref: "#/definitions/Office"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
          
  /organizations/{id}/offices/{oid}:
    get:
      description: |
        Get a specific `Office` of an `Organization`
      operationId: getOrganizationOfficeById
      summary: get organization office by id
      tags:
      - organization
      parameters:
      - name: id
        in: path
        description: ID of organization
        required: true
        type: integer
        format: int64
      - name: oid
        in: path
        description: ID of office
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successfull response
          schema:
            $ref: "#/definitions/Office"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
          
  /timesheet-entries:
    get:
      description: |
        Gets list of timesheet entries
      operationId: getTimesheetsEntries
      summary: get timesheet entries
      tags:
      - timesheet entry
      parameters:
      - $ref: "#/parameters/from"
      - $ref: "#/parameters/size"
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/TimesheetEntries"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
    
    post:
      description: |
        Create a Timesheet Entry for the specific timesheet
      operationId: createTimesheetEntry
      summary: create timesheet entry
      tags:
      - timesheet entry
      parameters:
      - name: entry
        description: timesheet entry to create
        in: body
        required: true
        schema:
          $ref: "#/definitions/NewTimesheetEntry"
      responses:
        201:
          description: Successfully created timesheet entry
          schema:
            $ref: "#/definitions/TimesheetEntry"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
                          
  /timesheets-entries/{id}:
    get:
      description: |
          Gets a specific `Timesheet` object.
      operationId: getTimesheetById
      summary: 'get timesheet by id'
      tags:
      - timesheet entry
      parameters: 
      - name: id
        in: path
        description: ID of timesheet entry to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/TimesheetEntry"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  Error:
    properties:
      code:
        type: string
      message:
        type: string
        
  NewOrganization:
    description: Organization post model
    required:
    - name
    properties:
      name:
        type: string
        description: name of the employer
        example: NHS
        
  Organization:
    description: An organization
    allOf:
    - $ref: '#/definitions/NewOrganization'
    properties:
      id:
        type: integer
        readOnly: true
        minimum: 0
        exclusiveMinimum: true
        example: 1234
      url:
        type: string
        readOnly: true
        example: http://api.bizhub.io/organizations/1234
      offices_url:
        type: string
        readOnly: true
        example: http://api.bizhub.io/organizations/1234/offices

  Organizations:
    type: array
    items:
      $ref: "#/definitions/Organization"
  
  NewOffice:
    description: New office model
    required:
    - address_line_1
    - town_or_city
    - country
    - postcode
    properties:
      address_line_1:
        type: string
        example: 2 Simple Street
      address_line_2:
        type: string
        example: Great Barnmouth
      town_or_city:
        type: string
        example: London
      county:
        type: string
        example: Greater London
      country:
        type: string
        example: United Kingdom
      postcode:
        type: string
        example: SE11 5JW
        
  OfficeIdentifier:
    properties:
      id:
        type: integer
        readOnly: true
        minimum: 0
        exclusiveMinimum: true
        example: 231
  
  Office:
    description: An office
    allOf:
    - $ref: "#/definitions/NewOffice"
    - $ref: "#/definitions/OfficeIdentifier"
    required:
    - address_line_1
    properties:
      url:
        type: string
        readOnly: true
        example: http://api.bizhub.io/organizations/1234/offices/231
      organization:
        $ref: "#/definitions/Organization"
        
  Offices:
    type: array
    items:
      $ref: "#/definitions/Office"
            
  TimesheetEntryBase:
    properties:
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
      break:
        type: number
        format: double
        example: 0.5
      rate_per_hour:
        type: number
        format: double
        example: 8.5
        
  NewTimesheetEntry:
    allOf: 
    - $ref: "#/definitions/TimesheetEntryBase"
    required:
    - start
    - end
    - break
    - rate_per_hour
    - employer_office
    properties:
      employer_office:
        $ref: "#/definitions/OfficeIdentifier"
      
  TimesheetEntry:
    allOf:
    - $ref: "#/definitions/TimesheetEntryBase"
    required:
    - start
    - end
    - break
    - rate_per_hour
    - employer_office
    properties:
      id:
        type: integer
        readOnly: true
        minimum: 0
        exclusiveMinimum: true
        example: 1234
      url:
        type: string
        readOnly: true
        example: http://api.bizhub.io/timesheets/1/entries/1234
      employer_office:
        $ref: "#/definitions/Office"
  
  TimesheetEntries:
    type: array
    items:
      $ref: "#/definitions/TimesheetEntry"

parameters:
  from:
    name: from
    in: query
    description: first element to return starting at 1
    required: false
    type: integer
    minimum: 0
    exclusiveMinimum: false
    default: 0

  size:
    name: size
    in: query
    description: max number of elements to return
    required: false
    type: integer
    minimum: 0
    exclusiveMinimum: true
    maximum: 100
    exclusiveMaximum: false
    default: 10

responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: "#/definitions/Error"