swagger: '2.0'

info:
  version: 1.0.0
  title: Bizhub
  description: Bizhub API resources and documentation

host: localhost:3000

basePath: /

schemes: 
  - http

consumes:
  - application/json

produces:
  - application/json

paths:
  /timesheets:
    get:
      description: |
        Gets list of `Timesheet` objects.
      operationId: getTimesheets
      summary: get timesheets
      tags:
      - timesheet
      parameters:
        - $ref: "#/parameters/from"
        - $ref: "#/parameters/size"
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Timesheets"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
                          
  /timesheets/{timesheetId}:
    get:
      description: |
          Gets a specific `Timesheet` object.
      operationId: getTimesheetById
      summary: 'get timesheet by id'
      tags:
      - timesheet
      parameters: 
      - $ref: "#/parameters/timesheetId"
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Timesheet"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  Error:
    properties:
      code:
        type: string
      message:
        type: string

  Timesheet:
    properties:
      id:
        type: integer
        readOnly: true
        minimum: 0
        exclusiveMinimum: true
      submit_date:
        type: string
        format: date-time
  Timesheets:
    type: array
    items:
      $ref: "#/definitions/Timesheet"

parameters:
  from:
    name: from
    in: query
    description: first element to return starting at 1
    required: false
    type: integer
    minimum: 0
    exclusiveMinimum: false
    default: 0

  size:
    name: size
    in: query
    description: max number of elements to return
    required: false
    type: integer
    minimum: 0
    exclusiveMinimum: true
    maximum: 100
    exclusiveMaximum: false
    default: 10

  timesheetId:
    name: timesheetId
    in: path
    description: ID of timesheet to return
    required: true
    type: integer
    format: int64

responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: "#/definitions/Error"